### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by imprs** [osrf/dynamic_config#4]
Hello,
      While building the package I'm facing following error:

`In file included from /home/pratik/catkin_ws/src/dynamic_config/src/gsoc/configuration/configuration_listener.cpp:36:0:
/home/pratik/catkin_ws/src/dynamic_config/include/gsoc/configuration/configuration_listener.h:41:33: fatal error: dynamic_config/Conf.h: No such file or directory
compilation terminated.
dynamic_config/CMakeFiles/dynamic_config.dir/build.make:110: recipe for target 'dynamic_config/CMakeFiles/dynamic_config.dir/src/gsoc/configuration/configuration_listener.cpp.o' failed
make[2]: *** [dynamic_config/CMakeFiles/dynamic_config.dir/src/gsoc/configuration/configuration_listener.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pratik/catkin_ws/src/dynamic_config/src/gsoc/configuration/configuration_client.cpp:36:0:
/home/pratik/catkin_ws/src/dynamic_config/include/gsoc/configuration/configuration_client.h:41:36: fatal error: dynamic_config/GetConf.h: No such file or directory
compilation terminated.
dynamic_config/CMakeFiles/dynamic_config.dir/build.make:134: recipe for target 'dynamic_config/CMakeFiles/dynamic_config.dir/src/gsoc/configuration/configuration_client.cpp.o' failed
make[2]: *** [dynamic_config/CMakeFiles/dynamic_config.dir/src/gsoc/configuration/configuration_client.cpp.o] Error 1
In file included from /home/pratik/catkin_ws/src/dynamic_config/src/gsoc/configuration/configuration_server.cpp:36:0:
/home/pratik/catkin_ws/src/dynamic_config/include/gsoc/configuration/configuration_server.h:41:36: fatal error: dynamic_config/GetConf.h: No such file or directory
`

Errors are due to GetConf.h and Conf.h. Are they missing?

Thanks.

**Comment by imprs** [comment]
When I added following lines in the CMakeLists.txt, I got it working.

`## Generate added messages and services with any dependencies listed here`
`generate_messages(`
  `DEPENDENCIES`
  `std_msgs  # and/or other packages containing depended messages`
`)`

Thanks.

**Comment by wjwwood** [comment]
Glad to hear you got it working. This was a prototype made by @abellagonzalo during an internship at OSRF, but is now no longer maintained.
